<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerusahaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'PT Indoprima Gemilang',
                'profile_perusahaan' => 'PT Indoprima Gemilang berdiri sejak 1976 di Surabaya, merupakan perusahaan manufaktur komponen otomotif (wiring harness, kabel baterai, saklar kombinasi, lapisan rem, dll) untuk berbagai pabrikan internasional seperti Daihatsu, Honda, Yamaha, Isuzu, Mitsubishi, dan lainnya. Bagian dari Indoprima Group.',
                'tipe_industri' => 'Swasta Nasional - Manufaktur Otomotif',
                'posisi_magang' => 'IT/System Development Intern',
                'min_ipk' => 3.00,
                'job_description' => 'Membantu pengembangan dan pemeliharaan sistem informasi internal perusahaan (plant 1, Nganjuk). Terlibat dalam analisis kebutuhan sistem, implementasi fitur, dan dokumentasi teknis.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Pengembangan SIPP - PT Link Apisindo Media & Dinas LH Kota Batu',
                'profile_perusahaan' => 'PT Link Apisindo Media adalah perusahaan IT di Malang yang bergerak di bidang penyediaan akses internet dan pengembangan sistem informasi. Berkolaborasi dengan Dinas Lingkungan Hidup Kota Batu untuk mengembangkan Sistem Informasi Penataan dan Penaatan (SIPP) lingkungan hidup.',
                'tipe_industri' => 'Swasta Nasional - IT & Software Development',
                'posisi_magang' => 'Backend Engineer / Frontend Engineer / AI Engineer / System Analyst',
                'min_ipk' => 3.00,
                'job_description' => 'Backend: pengembangan API, integrasi data, pengelolaan database. Frontend: pengembangan UI dashboard. AI: pengolahan data, pipeline AI/LLM. System Analyst: analisis kebutuhan, penyusunan SRS.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Pengembangan Platform Satu Peta Jatim - PT Link Apisindo Media & Dinas Kominfo Jatim',
                'profile_perusahaan' => 'PT Link Apisindo Media berkolaborasi dengan Dinas Kominfo Jawa Timur untuk mengembangkan Platform Satu Peta Jawa Timur, sistem pemetaan dan visualisasi data spasial skala provinsi berbasis WebGIS.',
                'tipe_industri' => 'Swasta Nasional - IT & Geospatial System',
                'posisi_magang' => 'Data Engineer / Backend Developer / Frontend Developer / AI & Data Engineer / DevOps Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Data: ETL data spasial, PostGIS. Backend: endpoint API, integrasi GIS. Frontend: dashboard peta interaktif, WebGIS. AI: model AI/LLM. DevOps: deployment, cloud (AWS), CI/CD.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT ARM Solusi',
                'profile_perusahaan' => 'PT ARM Solusi berdiri sejak 2001, merupakan perusahaan IT consulting di Jakarta dengan spesialisasi Django, Python, PostgreSQL, Odoo, dan Office Automation.',
                'tipe_industri' => 'Swasta Nasional - IT Consulting & Software Development',
                'posisi_magang' => 'Blockchain Engineer / Backend Developer / Data Engineer / Frontend Engineer / AI Engineer / Full-stack / DevOps',
                'min_ipk' => 3.00,
                'job_description' => 'Blockchain: Hyperledger Fabric. Backend: REST API. Data: preprocessing log transaksi. AI: pipeline ML, LLM. DevOps: deployment, Docker, AWS.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Pengembangan Platform Satu Peta Jatim - Batch 2',
                'profile_perusahaan' => 'Batch kedua dari kolaborasi PT Link Apisindo Media dengan Dinas Kominfo Jawa Timur untuk pengembangan Platform Satu Peta Jawa Timur.',
                'tipe_industri' => 'Swasta Nasional - IT & Geospatial System',
                'posisi_magang' => 'Data Engineer / Backend Developer / Frontend Developer / AI & Data Engineer / DevOps Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Data: ETL data spasial, manajemen PostGIS. Backend: API endpoint, FastAPI. Frontend: dashboard WebGIS. AI: prediksi geospasial. DevOps: cloud AWS, containerization.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Sarastya Agility Innovations',
                'profile_perusahaan' => 'Perusahaan konsultan bisnis & teknologi di Malang berfokus pada Business Agility, BPM, dan ERP. Membantu organisasi membangun tim lincah melalui pendekatan Agile dan Scrum.',
                'tipe_industri' => 'Swasta Nasional - IT Consulting & Business Process',
                'posisi_magang' => 'Backend / Frontend / Full Stack / DevOps / Data Analyst / Business Analyst / Network Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Pengembangan sistem ERP-BPM, deployment server, analisis data client, analisis keputusan bisnis, implementasi e-governance, dan pemeliharaan keamanan jaringan.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT Time Door Indonesia',
                'profile_perusahaan' => 'Startup IT di Bali menyediakan jasa web dev, mobile app, IoT, UI/UX, dan pendidikan teknologi (Timedoor Academy). Melayani 500+ klien.',
                'tipe_industri' => 'Swasta - Startup IT & Edutech',
                'posisi_magang' => 'Frontend Developer / QA Tester / AI Engineer / DevOps Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Frontend: UI responsif. QA: testing fungsional & otomatis. AI: modul ML. DevOps: deployment dan manajemen infrastruktur cloud.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT Maxchat Inovasi Indonesia',
                'profile_perusahaan' => 'Meta Official Business Partner di Malang untuk layanan WhatsApp Business API. Menyediakan solusi Omnichannel CRM dan chatbot.',
                'tipe_industri' => 'Swasta Nasional - IT & SaaS',
                'posisi_magang' => 'Mobile Developer (Flutter) / Backend Developer / QA Automation',
                'min_ipk' => 3.00,
                'job_description' => 'Mobile: aplikasi cross-platform. Backend: layanan API. QA: pengujian otomatis dan dokumentasi bug produk Maxchat.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Politeknik Batu',
                'profile_perusahaan' => 'Perguruan tinggi vokasi di Batu, Jawa Timur. Membutuhkan magang untuk mendukung pengembangan aplikasi internal.',
                'tipe_industri' => 'Instansi Pendidikan - Perguruan Tinggi',
                'posisi_magang' => 'Programmer / Quality Assurance (QA) / Tester',
                'min_ipk' => 3.00,
                'job_description' => 'Programmer: fitur baru & bugfix Flutter/Web. Tester: pengujian fungsional dan dokumentasi hasil testing.',
                'status_magang' => 'Unpaid',
            ],
            [
                'name' => 'Ariverse Studio (PT Studio Karya Semesta)',
                'profile_perusahaan' => 'Studio game di Malang berfokus pada game PC/Console/Mobile, VR/AR, dan gamified learning.',
                'tipe_industri' => 'Swasta - Game Developer & Software House',
                'posisi_magang' => 'Game Programmer / Full Stack Developer / Frontend Developer Intern',
                'min_ipk' => 3.00,
                'job_description' => 'Game: gameplay & Unity debugging. Fullstack: app Flutter/React/Laravel. Frontend: UI responsif web/mobile.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Humas POLINEMA',
                'profile_perusahaan' => 'Unit pengelola komunikasi publik Polinema. Membutuhkan magang untuk analitik data digital media.',
                'tipe_industri' => 'Instansi Pendidikan - Perguruan Tinggi (Polinema)',
                'posisi_magang' => 'Data Analyst / Social Media Analyst',
                'min_ipk' => 3.00,
                'job_description' => 'Analisis data Google Analytics & social media. Visualisasi insight strategi komunikasi dan laporan berbasis data.',
                'status_magang' => 'Unpaid',
            ],
            [
                'name' => 'PT Alfath Corporation',
                'profile_perusahaan' => 'Perusahaan pengembangan solusi digital berbasis AI, chatbot, dan otomasi proses bisnis.',
                'tipe_industri' => 'Swasta Nasional - IT & Software Development',
                'posisi_magang' => 'Fullstack Developer (AI & Automation)',
                'min_ipk' => 3.00,
                'job_description' => 'Pengembangan aplikasi fullstack terintegrasi n8n (automation), WebSocket (real-time), dan AI chatbot.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT UTERO KREATIF INDONESIA',
                'profile_perusahaan' => 'Utero Technology adalah perusahaan di Malang mengembangkan solusi web/mobile berbasis data.',
                'tipe_industri' => 'Swasta Nasional - IT & Software Development',
                'posisi_magang' => 'Fullstack JS Developer / Software Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Pengembangan solusi web/mobile skalabel. Terlibat analisis kebutuhan bisnis dan problem solving berbasis data.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'The Himana Hotel & Mall Malang City Point',
                'profile_perusahaan' => 'Hotel bintang di Malang City Point menyediakan layanan perhotelan premium.',
                'tipe_industri' => 'Swasta Nasional - Hospitality & Hotel',
                'posisi_magang' => 'Magang Perhotelan (OJT) - berbagai departemen',
                'min_ipk' => 0.00,
                'job_description' => 'Operasional harian di Front Office, Housekeeping, atau F&B. Melayani tamu dan belajar standar hotel.',
                'status_magang' => 'Unpaid',
            ],
            [
                'name' => 'Wakil Direktur 4 Politeknik Negeri Malang',
                'profile_perusahaan' => 'Membidangi kerjasama institusi. Mendukung pengembangan sistem web dan manajemen data kerjasama.',
                'tipe_industri' => 'Instansi Pendidikan - Perguruan Tinggi (Polinema)',
                'posisi_magang' => 'Web Developer / Data Engineer / Data Analyst',
                'min_ipk' => 3.00,
                'job_description' => 'Web: modifikasi sistem kerjasama. Data Eng: storage dokumen. Analyst: pengolahan data kerjasama.',
                'status_magang' => 'Unpaid',
            ],
            [
                'name' => 'PT Rekaindo Global Jasa',
                'profile_perusahaan' => 'Konsultan engineering & support komponen kereta api di Madiun (afiliasi PT INKA).',
                'tipe_industri' => 'Swasta (afiliasi BUMN) - Engineering & Perkeretaapian',
                'posisi_magang' => 'Frontend Developer / Backend Developer / UI/UX Designer',
                'min_ipk' => 3.00,
                'job_description' => 'Digitalisasi proses bisnis: pengembangan antarmuka, API, database, normalisasi tabel, dan desain UI/UX.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT JST Indonesia',
                'profile_perusahaan' => 'Manufaktur komponen elektronik & wiring harness otomotif. Fokus pada proyek digitalisasi & AI internal.',
                'tipe_industri' => 'Swasta (PMA Jepang) - Manufaktur Elektronik & Otomotif',
                'posisi_magang' => 'IT Staff / AI & Digitalization Intern',
                'min_ipk' => 3.00,
                'job_description' => 'Mendukung otomasi proses, solusi AI/ML, pembuatan dashboard, dan modernisasi sistem IT produksi.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT Green Energi Utama',
                'profile_perusahaan' => 'Perusahaan bidang energi terbarukan di Indonesia.',
                'tipe_industri' => 'Swasta Nasional - Energi Terbarukan',
                'posisi_magang' => 'Magang Teknologi Informasi / Engineering',
                'min_ipk' => 3.00,
                'job_description' => 'Mendukung operasional teknis sesuai bidang kompetensi akademik mahasiswa di perusahaan.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'UPA Bahasa Polinema',
                'profile_perusahaan' => 'Unit pelayanan bahasa menyediakan kursus, tes TOEIC/TOEFL, dan jasa terjemahan.',
                'tipe_industri' => 'Instansi Pendidikan - Perguruan Tinggi (Polinema)',
                'posisi_magang' => 'Web Developer / Content Creator',
                'min_ipk' => 3.00,
                'job_description' => 'Pengembangan web kursus & pembelajaran mandiri. Pembuatan konten digital & company profile.',
                'status_magang' => 'Unpaid',
            ],
            [
                'name' => 'PT Peruri Wira Timur',
                'profile_perusahaan' => 'Anak perusahaan Perum Peruri (BUMN) di Surabaya bidang security printing (ijazah, dokumen sekuriti).',
                'tipe_industri' => 'BUMN (Anak Perusahaan) - Security Printing',
                'posisi_magang' => 'Backend/Fullstack Developer - Sistem Internal',
                'min_ipk' => 3.00,
                'job_description' => 'Pengembangan sistem internal fokus digitalisasi dokumen, Laravel, REST API, dan manajemen database.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT Sekuriti Siber Indonesia',
                'profile_perusahaan' => 'Nemo Security fokus pada SOC, compliance, dan monitoring keamanan jaringan.',
                'tipe_industri' => 'Swasta Nasional - Cybersecurity',
                'posisi_magang' => 'SOC Analyst / IT Compliance',
                'min_ipk' => 3.00,
                'job_description' => 'Monitoring ancaman siber (SIEM), analisis insiden, deteksi respons, dan dokumentasi audit internal.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT PAL Indonesia (Persero)',
                'profile_perusahaan' => 'BUMN galangan kapal terbesar di Surabaya memproduksi kapal perang, niaga, dan selam.',
                'tipe_industri' => 'BUMN - Industri Maritim & Pertahanan',
                'posisi_magang' => 'Cybersecurity / Infrastruktur TI / Pengembangan Aplikasi',
                'min_ipk' => 3.00,
                'job_description' => 'Keamanan info, manajemen server/jaringan, analisis kebutuhan, implementasi dan testing aplikasi.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT Industri Kereta Api / PT INKA (Persero)',
                'profile_perusahaan' => 'BUMN manufaktur kereta api terbesar di Asia Tenggara berlokasi di Madiun.',
                'tipe_industri' => 'BUMN - Manufaktur Perkeretaapian',
                'posisi_magang' => 'Software Developer / Data Analyst / IoT & AI Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Dev: sistem Laravel. Analyst: Looker Studio. IoT/AI: asset tracker, digital twin, dan simulasi layout.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Atria Hotel Malang',
                'profile_perusahaan' => 'Hotel bintang 4 di Malang. Departemen IT mencakup software, network, dan data analytics.',
                'tipe_industri' => 'Swasta Nasional - Hospitality & Hotel',
                'posisi_magang' => 'IT Intern - Software / Network / Data Analyst',
                'min_ipk' => 3.00,
                'job_description' => 'Mendukung pemeliharaan sistem hotel, manajemen jaringan, dan pengolahan data operasional harian.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT Intelix Global Crossing',
                'profile_perusahaan' => 'Perusahaan IT di Malang mengembangkan produk digital end-to-end dari analisis hingga deployment.',
                'tipe_industri' => 'Swasta Nasional - IT & Software Development',
                'posisi_magang' => 'Frontend / Backend / QA Tester / System Analyst',
                'min_ipk' => 3.00,
                'job_description' => 'Terlibat langsung dalam siklus pengembangan produk nyata: UI, backend dev, testing, dan analisis.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'PT Dutakom Wibawa Putra',
                'profile_perusahaan' => 'Penyedia layanan ICT (D-Net) di Surabaya. Fokus OLT management, data center, dan solusi enterprise.',
                'tipe_industri' => 'Swasta Nasional - ICT & Telekomunikasi',
                'posisi_magang' => 'Fullstack / Backend / Frontend Programmer / IT Infra / Data Center Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'R&D Dashboard OLT, prototipe REST/GraphQL, helpdesk IT, manajemen mutu ISO 27001, instalasi DC.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'CV Harsyad Utama (Harsyad Teknologi)',
                'profile_perusahaan' => 'Software house di Malang mengerjakan pengembangan aplikasi web internal dan eksternal.',
                'tipe_industri' => 'Swasta Nasional - Software House',
                'posisi_magang' => 'Web Developer / Software Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Siklus penuh pengembangan web: analisis kebutuhan, perancangan, frontend-backend dev, dan testing.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'DOT Indonesia',
                'profile_perusahaan' => 'Software house terkemuka mengembangkan aplikasi web, mobile, dan AI untuk klien nasional/global.',
                'tipe_industri' => 'Swasta Nasional - Software House & IT Consulting',
                'posisi_magang' => 'Backend / Frontend / AI Engineer / System Analyst / UI-UX Engineer',
                'min_ipk' => 3.00,
                'job_description' => 'Pengembangan API, UI interaktif, model AI/ML, dokumentasi teknis, dan desain pengalaman pengguna.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'Oyitok Group',
                'profile_perusahaan' => 'Grup bisnis yang sedang melakukan digitalisasi administrasi dan analitik data internal.',
                'tipe_industri' => 'Swasta Nasional - Bisnis Umum / Digitalisasi',
                'posisi_magang' => 'Data Analyst / System Administration',
                'min_ipk' => 3.00,
                'job_description' => 'Analisis data keputusan bisnis, pengembangan sistem administrasi digital, dan laporan visualisasi.',
                'status_magang' => 'Paid',
            ],
            [
                'name' => 'CV DB KLIK',
                'profile_perusahaan' => 'DB Group adalah penyedia solusi IT retail (#OneStopITSolution) berdiri sejak tahun 2000.',
                'tipe_industri' => 'Swasta Nasional - IT Solution & Retail',
                'posisi_magang' => 'Dev / UI-UX / System Analyst / Data Analyst / Website Developer',
                'min_ipk' => 3.00,
                'job_description' => 'Pengembangan fitur web, wireframe Figma, analisis tren data (Tableau), dan dokumentasi UML/BRD.',
                'status_magang' => 'Paid',
            ],
        ];

        foreach ($data as $item) {
            DB::table('perusahaan')->insert(array_merge($item, [
                'duration_months' => '3 - 6',
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}